### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by ImmanuelSamuel** [MandyMo/HAMR#2]
Great work! Would you mind responding with a code snippet to run this. I have been trying to just input an image and get an output pose but its taking me a while to sift through the code.

**Comment by MandyMo** [comment]
Thank you for your strong support.

Currently, we can't release the training code and the data-loader.

Maybe you should train our model on RHD&STB datasets. (You may download these benchmarks from the official website.)

We can offer other helps which we can provide.
