### ISSUE TITLE
Confusing about the parameter Rs returning from the ManoNetbase 

### ISSUE THREAD

**Issue by Elody-07** [MandyMo/HAMR#4]
I'm trying to build the model and is getting confused about the parameter Rs coming from the mano layer. What's the utility and meaning of Rs? Is it necessary to return from the network ? 
Thanks for your excellent work!

**Comment by MandyMo** [comment]
Good question.

Rs is the pose parameter of the parametric model - MANO.

For more information, please read the original SMPL and MANO paper.

**Comment by Elody-07** [comment]
Thanks for your reply! There's another question about the parameter j3d. Are they computed in world coordinate? Do we need to use camera intrinsic given in the RHD annotation? In the paper you compute ground truth of camera using ground truth 2D and 3D joints.

**Comment by MandyMo** [comment]
All the 3D joint locations are in camera space.

One more thing thatI shall point out here, the root joints is wrist. (Similar to ZB's ICCV 2017 paper)

The process of estimating camera parameters only involves aligned 3D joints and 2D key points.

**Comment by Elody-07** [comment]
I notice that in your released code there are two project types: perspective and orthogonal, whose camera parameters are [f, tx, ty, tz, dx, dy] and [s, tx, ty] respectively. In the case of perspective projection, could I just use camera intrinsic and extrinsic parameters as camera ground truth? And in the latter case, do we compute camera ground truth using annotation 2D and 3D joints? 
Thanks again for your reply!
