### ISSUE TITLE
Is there a pre-trained model to play

### ISSUE THREAD

**Issue by momo1986** [MandyMo/HAMR#5]
Thanks for sharing.
Is there a pre-trained model to try and play.

I want to use it in my own dataset.

**Comment by MandyMo** [comment]
I am sorry, pre-trained model can't be released at this moment.

**Comment by MLsmaller** [comment]
> I am sorry, pre-trained model can't be released at this moment.

May I ask if I can test your model in my own data set now? When will this part of code be released?
Thank you for you reply.
